sudo: required

services:
  - docker

os:
- linux
- osx

language: rust

rust:
- stable
- beta
- nightly

script:
- cargo doc
- make unit-tests
- (cd cli && cargo build)
- make debug-docker-db
- make integration-tests
