sudo: required

services:
  - docker

os:
- linux
- osx

language: rust

rust:
- stable
- beta
- nightly

script:
- cargo doc
- make unit-tests
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then make integration-tests; fi
